name: Telegram Monitor Bot
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '*/5 * * * *'  # Exécution toutes les 5 minutes

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install telethon python-dotenv
          
      - name: Run bot
        env:
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          PHONE_NUMBER: ${{ secrets.PHONE_NUMBER }}
          TARGET_USER: ${{ secrets.TARGET_USER }}
        run: |
          python telegram_monitor.py
